# Copyright 2025 The Formal Conjectures Authors.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     https://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name = "formal_conjectures"
keywords = ["math"]
defaultTargets = ["FormalConjectures"]
testDriver = "FormalConjecturesTest"

[leanOptions]
# Pretty-prints `fun a ↦ b`
pp.unicode.fun = true
# Don't assume a typo is a new variable
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "25ce63313608"

[[require]]
name = "brownian-motion"
git = "https://github.com/RemyDegenne/brownian-motion"
rev = "91267abd71bd32e9ef6c10c9359938f24a3e1f38"

[[require]]
name = "kolmogorov_extension4"
git = "https://github.com/RemyDegenne/kolmogorov_extension4"
rev = "2c2b44e55251"

# We make this a separate library so that we can apply different lean options.
[[lean_lib]]
name = "FormalConjecturesForMathlib"

[[lean_lib]]
name = "FormalConjecturesTest"
# Switch off warnings generated by `sorry`
leanOptions = { warn.sorry = false }

[[lean_lib]]
name = "FormalConjectures"
globs = ["FormalConjectures.+"]
# Switch off warnings generated by `sorry`
leanOptions = { warn.sorry = false }

[[lean_exe]]
name = "extract_names"
srcDir = "scripts"
root = "extract_names"
exeName = "extract_names"
supportInterpreter = true
