#!/usr/bin/env python3
"""Generate the exact bit-vector certificate for the LRC(14) terminal lemma."""

from fractions import Fraction
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = (
    ROOT
    / "FormalConjectures"
    / "Wikipedia"
    / "LonelyRunnerConjecture"
    / "FiniteRigidity.lean"
)


def robust_patterns() -> list[tuple[int, ...]]:
    endpoints = sorted(
        {
            Fraction(a, 15 * i)
            for i in range(1, 15)
            for a in range(15 * i + 1)
        }
    )
    cells = [
        (left, right)
        for left, right in zip(endpoints, endpoints[1:])
        if right - left >= Fraction(1, 900)
    ]
    assert len(endpoints) - 1 == 960
    assert len(cells) == 270

    patterns = []
    for left, right in cells:
        theta = (left + right) / 2
        pattern = tuple(
            int(15 * ((i * theta) % 1))
            for i in range(1, 15)
        )
        patterns.append(pattern)
    return patterns


def conjunction(lines: list[str], indent: str = "  ") -> str:
    if len(lines) == 1:
        return lines[0]
    midpoint = len(lines) // 2
    left = conjunction(lines[:midpoint], indent + "  ")
    right = conjunction(lines[midpoint:], indent + "  ")
    return f"({left} ∧\n{indent}{right})"


def blocking_clause(multiplier: int, modulus: int, pattern: tuple[int, ...]) -> str:
    terms = []
    for i, bin_value in enumerate(pattern):
        terms.extend(
            f"c.c{i} = {residue}"
            for residue in range(modulus)
            if (multiplier * residue + bin_value) % 15 in (0, 14)
        )
    assert terms
    return "(" + " ∨ ".join(terms) + ")"


def affine_terms(modulus: int) -> list[str]:
    return [
        f"c.c{i}.zeroExtend 8 = (c.c0.zeroExtend 8) * {i + 1} % {modulus}"
        for i in range(14)
    ]


def generate() -> str:
    patterns = robust_patterns()
    fields = "\n".join(f"  c{i} : BitVec 3" for i in range(14))
    bounds = conjunction([f"c.c{i}.ult bound" for i in range(14)], "    ")
    blocks_three = conjunction(
        [blocking_clause(3, 5, pattern) for pattern in patterns], "    "
    )
    blocks_five = conjunction(
        [blocking_clause(5, 3, pattern) for pattern in patterns], "    "
    )
    affine_three = conjunction(affine_terms(3), "    ")
    affine_five = conjunction(affine_terms(5), "    ")
    destructure = ", ".join(f"c{i}" for i in range(14))

    return f'''/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjectures.Util.ProblemImports

/-!
# Finite rigidity certificate for the lonely runner terminal argument

This file is generated by `scripts/generate_lonely_runner_finite_rigidity.py`.
It contains the 270 phase patterns arising from breakpoint cells of length at
least `1 / 900`, encoded as bit-vector clauses for Lean's verified SAT checker.
-/

namespace LonelyRunnerConjecture.CompositeTerminalRigidity

set_option maxRecDepth 100000
set_option maxHeartbeats 2000000

/-- Fourteen residues stored in eight-bit words. -/
structure BVResidueVector where
{fields}

/-- Every stored residue is smaller than `bound`. -/
def AllLt (bound : BitVec 3) (c : BVResidueVector) : Prop :=
  {bounds}

/-- All 270 robust patterns are blocked for multiplier three. -/
def BlocksRobustMultiplierThree (c : BVResidueVector) : Prop :=
  {blocks_three}

/-- All 270 robust patterns are blocked for multiplier five. -/
def BlocksRobustMultiplierFive (c : BVResidueVector) : Prop :=
  {blocks_five}

/-- Affine reduction modulo three, with the first coordinate as slope. -/
def AffineModThree (c : BVResidueVector) : Prop :=
  {affine_three}

/-- Affine reduction modulo five, with the first coordinate as slope. -/
def AffineModFive (c : BVResidueVector) : Prop :=
  {affine_five}

/-- Verified finite rigidity for multiplier five and modulus three. -/
@[category test, AMS 11]
theorem blocks_robust_multiplier_five_forces_affine_mod_three
    (c : BVResidueVector) (hbound : AllLt 3 c)
    (hblocks : BlocksRobustMultiplierFive c) : AffineModThree c := by
  rcases c with ⟨{destructure}⟩
  simp only [AllLt, BlocksRobustMultiplierFive, AffineModThree] at *
  bv_decide

/-- Verified finite rigidity for multiplier three and modulus five. -/
@[category test, AMS 11]
theorem blocks_robust_multiplier_three_forces_affine_mod_five
    (c : BVResidueVector) (hbound : AllLt 5 c)
    (hblocks : BlocksRobustMultiplierThree c) : AffineModFive c := by
  rcases c with ⟨{destructure}⟩
  simp only [AllLt, BlocksRobustMultiplierThree, AffineModFive] at *
  bv_decide

end LonelyRunnerConjecture.CompositeTerminalRigidity
'''


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generate())


if __name__ == "__main__":
    main()
